version: "3"
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile_mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: mysql_container
    ports:
      - 3306:3306
    restart: always

  parser:
    build:
      context: .
      dockerfile: Dockerfile_parser
    container_name: parser_container
    restart: always
    links:
      - mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile_api
    container_name: api_container
    ports:
      - 5000:5000
    restart: always
    links:
      - mysql
      - parser
