version: "3"
services:
  mysql:
    build:
      context: .
      dockerfile: mysql/Dockerfile
    container_name: mysql_container
    ports:
      - 3306:3306
    restart: always

  parser:
    build:
      context: .
      dockerfile: parser/Dockerfile
    container_name: parser_container
    restart: always
    links:
      - mysql

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api_container
    ports:
      - 5000:5000
    restart: always
    links:
      - mysql
      - parser
